services:
  hh-bumper:
    image: hh-bumper
    container_name: hh-bumper
    restart: unless-stopped
    ports:
      - "52888:52888"
    env_file:
      - ./.env
    volumes:
      - ./tokens.json:/app/tokens.json
      - /etc/localtime:/etc/localtime:ro
